#!/bin/bash

set -e

yarn setup
yarn lint

openwisp-qa-check --skip-checkmigrations \
                  --skip-checkmakemigrations \
                  --skip-black \
                  --skip-flake8 \
                  --skip-isort \
                  --skip-checkendline
