---
name: "default name"
slug: "default"

settings:
  mobile_phone_verification: false
  subscriptions: false

# configuration variables for the server app
server:
  # put the URL of openwisp-radius here
  host: "http://127.0.0.1:8000"
  uuid: organization_uuid
  secret_key: organization_secret_key
  timeout: 2 #request timeout period in seconds

# configuration variables for the client
# Path of all the assets should be defined relative to the organization's folder
# in assets directory.
client:

  auto_login: True

  # path of favicon
  favicon: "favicon.png"

  # path of the custom css file or files relative to organization's 
  # folder in assets directory.
  css:
    - "index.css"
  js:
    - "index.js"
  languages:
    - text: "english"
      slug: "en"
  default_language: "en"
  components:
    header:
      logo:
        url: "openwisp-logo-black.svg" # logo url
        alternate_text: "openwisp"
      links:
        - text:
            en: "Sign In"
          url: "/{orgSlug}/login"
          authenticated: false
        - text:
            en: "Sign Up"
          url: "/{orgSlug}/registration"
          authenticated: false
        - text:
            en: "Change password"
          url: "/{orgSlug}/change-password"
          authenticated: true
          methods_excluded:
            - saml
            - social_login

    footer:
      links:
        - text:
            en: "link-1"
          url: "https://link-1.com"
          authenticated: false
        - text:
            en: "link-2"
          url: "https://link-2.com"
          authenticated: true
          verified: false
        - text:
            en: "link-3"
          url: "https://link-3.com"
          authenticated: true
          verified: true
      after_html:
        en: "Copyright"

    registration_form:
      input_fields:
        phone_number: {}
        username:
          pattern: '[a-zA-Z@.+\-_\d]{1,150}'
        email:
          pattern: '.+@.+\..+'
        password:
          pattern: ".{6,}"
        password_confirm:
          pattern: ".{6,}"
        first_name:
          setting: "disabled"
        last_name:
          setting: "disabled"
        birth_date:
          setting: "disabled"
        location:
          pattern: '[a-zA-Z@.+\-_\d]{1,150}'
          setting: "disabled"
        country:
          pattern: '[a-zA-Z@.+\-_\d\s]{1,150}'
        zipcode: {}
        street: {}
        city: {}
        tax_number:
          pattern: '[a-zA-Z@.+\-_\d]{1,150}'
      additional_info_text: true
      links:
        login: true

    password_reset_form:
      additional_text: true
      input_fields:
        email:
          pattern: '.+@.+\..+'
      contact_text: true
      login_page_link: true

    password_reset_confirm_form:
      additional_text: true
      input_fields:
        password:
          pattern: ".{6,}"
        password_confirm:
          pattern: ".{6,}"
      contact_text: true
      login_page_link: true

    contact_page:
      email: "support@openwisp.co"
      helpdesk: "+789 948 564"
      social_links:
        - alt:
            en: "twitter"
          icon: "twitter.svg"
          url: "https://twitter.com/openwisp"
        - alt:
            en: "facebook"
          icon: "facebook.svg"
          url: "https://facebook.com/openwisp"

    status_page:
      links:
        - text:
            en: "Change your password"
          url: "/{orgSlug}/change-password/"

    login_form:
      social_login:
        links:
          - text:
              en: "Login with Facebook"
            url: "#facebook"
            icon: "facebook.svg"
          - text:
              en: "Login with Google"
            icon: "google.svg"
            url: "#google"
          - text:
              en: "Login with Twitter"
            icon: "twitter.svg"
            url: "#twitter"
      input_fields:
        username:
          type: "email"
          pattern: '.+@.+\..+'
        password:
          pattern: ".{6,}"
        remember_me:
          value: true
      additional_info_text: true
      buttons:
        register: true
      links:
        forget_password: true

    password_change_form:
      input_fields:
        password1:
          pattern: ".{6,}"
        password2:
          pattern: ".{6,}"

    404_page:
      heading: true
      sub_heading: true
      message: true
      homepage_link: true

    captive_portal_login_form:
      method: post
      action: http://localhost:8000/captive-portal-mock/login/
      fields:
        username: auth_user
        password: auth_pass
      macaddr_param_name: macaddr
      additional_fields:
        - name: zone
          value: zone_name
        - name: redirurl
          value: http://localhost:8080/default/status
        - name: accept
          value: accept

    captive_portal_logout_form:
      method: post
      action: http://localhost:8000/captive-portal-mock/logout/
      fields:
        id: logout_id
      additional_fields: []
      logout_by_session: true
      wait_after: 3000

  privacy_policy:
    en: "privacy-en.md"
  terms_and_conditions:
    en: "terms-en.md"
