export const PARSE_ORGANIZATIONS = "PARSE_ORGANIZATIONS";
export const SET_AUTHENTICATION_STATUS = "SET_AUTHENTICATION_STATUS";
export const SET_LANGUAGE = "SET_LANGUAGE";
export const SET_ORGANIZATION_CONFIG = "SET_ORGANIZATION_CONFIG";
export const SET_ORGANIZATION_STATUS = "SET_ORGANIZATION_STATUS";
export const SET_USER_DATA = "SET_USER_DATA";
export const SET_PAGE_TITLE = "SET_PAGE_TITLE";
