export const PARSE_ORGANIZATIONS = "PARSE_ORGANIZATIONS";
export const SET_ORGANIZATION_CONFIG = "SET_ORGANIZATION_CONFIG";
export const SET_ORGANIZATION_STATUS = "SET_ORGANIZATION_STATUS";
export const SET_LANGUAGE = "SET_LANGUAGE";
