export const PARSE_ORGANIZATIONS = "PARSE_ORGANIZATIONS";
export const SET_AUTHENTICATION_STATUS = "SET_AUTHENTICATION_STATUS";
export const SET_LANGUAGE = "SET_LANGUAGE";
export const SET_ORGANIZATION_CONFIG = "SET_ORGANIZATION_CONFIG";
export const SET_ORGANIZATION_STATUS = "SET_ORGANIZATION_STATUS";
export const SET_MOBILE_PHONE_VERIFICATION_STATUS =
  "SET_MOBILE_PHONE_VERIFICATION_STATUS";
export const IS_ACTIVE = "IS_ACTIVE";
export const SET_USER_DATA = "SET_USER_DATA";
